### ISSUE TITLE
Setting up a second table causes an error in the lambda function

### ISSUE THREAD

**Issue by Altavious** [awslabs/dynamodb-continuous-backup#21]
An error occurred (ResourceConflictException) when calling the CreateFunction operation: Function already exist: LambdaStreamToFirehose: ClientError
Traceback (most recent call last):
File "/var/task/index.py", line 28, in event_handler
backup.configure_table(dynamo_table_name)
File "/var/task/dynamo_continuous_backup.py", line 354, in configure_table
ensure_update_stream_event_source(dynamo_stream_arn)
File "/var/task/dynamo_continuous_backup.py", line 229, in ensure_update_stream_event_source
function_arn = ensure_lambda_streams_to_firehose()
File "/var/task/dynamo_continuous_backup.py", line 285, in ensure_lambda_streams_to_firehose
Publish=True
File "/var/runtime/botocore/client.py", line 159, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 494, in _make_api_call
raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (ResourceConflictException) when calling the CreateFunction operation: Function already exist: LambdaStreamToFirehose

**Comment by IanMeyers** [comment]
That's very strange, because the deployer first checks that the function is already there before proceeding. Could a race condition on first run, but either way I've not fixed in 1.5: https://github.com/awslabs/dynamodb-continuous-backup/commit/4a06b3d84da2a47139cfbecf6d098924981e33ec
